name: Send EPUB to Kindle Daily

on:
  schedule:
    - cron: '0 1 * * *'  # 1 AM UTC = 7 AM IST
  workflow_dispatch:      # Allows manual triggering

jobs:
  send-epub:
    runs-on: ubuntu-latest

    env:
      KINDLE_EMAIL: pramodshah6797_37OKiT@kindle.com
      SENDER_EMAIL: ajaykg6917@gmail.com
      GIT_REPO_URL: https://gitlab.com/Monkfishare/2025.git

    steps:
    - name: Install Calibre
      run: |
        sudo apt update
        sudo apt install -y calibre
    - name: Clone EPUB Repo
      run: |
        git clone $GIT_REPO_URL repo

    - name: Find and Send Latest EPUB
      run: |
        YYY=$(date +%Y)
        cd repo/TE/$YYY || exit 1
        latest_folder=$(ls -d [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] | sort -r | head -n 1)
        cd "$latest_folder" || exit 1
        latest_epub=$(ls -t *.epub | head -n 1)
        if [ -z "$latest_epub" ]; then
            echo "No EPUB file found."
            exit 1
        fi
        echo "Latest EPUB file found: $latest_epub"
        /usr/bin/calibre-smtp \
          --attachment "$latest_epub" \
          --relay smtp.gmail.com \
          --port 587 \
          --username "${{ secrets.GMAIL_USER }}" \
          --password "${{ secrets.GMAIL_APP_PASSWORD }}" \
          "$SENDER_EMAIL" "$KINDLE_EMAIL" \
          "Your Daily Economist" "Attached is the latest Economist EPUB."
        